import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedChangePasswordWidget.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedCreateNewPasswordWidget.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedFrameWidget8.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedRectangle1Widget14.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedRectangle8Widget6.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedSaveWidget.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedVector34Widget3.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedWavy_Cst02_Single06Converted1Widget.dart';
import 'package:untitled5/untitledapp/generatednewpasswordwidget/generated/GeneratedYourNewPasswordMustBeDifferentFromPreviouslyusedPasswor.dart';

import '../../helpers/transform/transform.dart';
import '../generatedsigninwidget/generated/GeneratedCONFIRMPASSWORDWidget.dart';
import '../generatedsigninwidget/generated/GeneratedPASSWORDWidget1.dart';
import '../generatedsigninwidget/generated/GeneratedVector22Widget.dart';
import '../generatedsigninwidget/generated/GeneratedVector23Widget.dart';
import 'generated/GeneratedFiunlockWidget1.dart';
import 'generated/GeneratedFiunlockWidget2.dart';


/* Frame New Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewPasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget14(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 305.0,
                              height: 27.0,
                              child: GeneratedCreateNewPasswordWidget(),
                            ),
                            Positioned(
                              left: -14.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 456.0,
                              height: 111.0,
                              child: GeneratedFrameWidget8(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 841.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 44.0,
                              child: GeneratedRectangle8Widget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.633177570093458;

                                final double height = constraints.maxHeight *
                                    0.029157667386609073;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18925233644859812,
                                      y: constraints.maxHeight *
                                          0.9200863930885529,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSaveWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 45.5,
                              top: 613.5,
                              right: null,
                              bottom: null,
                              width: 331.0,
                              height: 0.0,
                              child: GeneratedVector22Widget(),
                            ),
                            Positioned(
                              left: 45.5,
                              top: 681.5,
                              right: null,
                              bottom: null,
                              width: 331.0,
                              height: 0.0,
                              child: GeneratedVector23Widget(),
                            ),
                            Positioned(
                              left: 83.0,
                              top: 589.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 18.0,
                              child: GeneratedPASSWORDWidget1(),
                            ),
                            Positioned(
                              left: 83.0,
                              top: 658.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 15.0,
                              child: GeneratedCONFIRMPASSWORDWidget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 580.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 22.0,
                              child: GeneratedFiunlockWidget1(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 648.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 22.0,
                              child: GeneratedFiunlockWidget2(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 446.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 86.0,
                              child:
                                  GeneratedYourNewPasswordMustBeDifferentFromPreviouslyusedPasswor(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 745.0,
                              right: null,
                              bottom: null,
                              width: 173.0,
                              height: 20.0,
                              child: GeneratedChangePasswordWidget(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 769.0,
                              right: null,
                              bottom: null,
                              width: 174.00286865234375,
                              height: 0.0,
                              child: GeneratedVector34Widget3(),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 109.0,
                              right: null,
                              bottom: null,
                              width: 317.0,
                              height: 315.0,
                              child:
                                  GeneratedWavy_Cst02_Single06Converted1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
