import 'package:flutter/material.dart';
import 'package:untitled5/theme/themee.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/GeneratedSigninWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedCONTINUEASAGUESTWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedDonthaveanaccountSignupWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedFORGOTWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedFiunlockWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedFiuserWidget1.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedFrameWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedLoginWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedPASSWORDWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedRectangle1Widget5.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedUSERNAMEWidget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedVector19Widget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedVector20Widget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedVector21Widget.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedVectorWidget2.dart';
import 'package:untitled5/untitledapp/generatedsignupwidget/generated/GeneratedLoginWidget.dart';


/* Frame Sign Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      decoration: BoxDecoration(
                        color: Colors.white,
                      ),
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget5(),
                            ),
                            Positioned(
                              left: 269.4127502441406,
                              top: -107.6426010131836,
                              right: null,
                              bottom: null,
                              width: 239.564697265625,
                              height: 251.9700164794922,
                              child: GeneratedVectorWidget2(),
                            ),
                            Positioned(
                              top: 230,
                              left: 40,
                              right: 255,
                              bottom: null,
                              child: Text('Login',
                                style: TextStyle(
                                  fontSize: 38,
                                  fontWeight: FontWeight.w700,
                                  fontFamily: 'Montserrat',
                                  color: Colors.black,
                                ),),
                            ),
                            Positioned(
                              top: 303,
                              left: 40,
                              right: 136,
                              bottom: null,
                              child: Text('Sign in to have full access',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.w500,
                                  fontFamily: 'Montserrat',
                                  color: Colors.black,
                                ),),
                            ),
                            Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                  Padding(
                                    padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 16),
                                    child: TextFormField(
                                      decoration: const InputDecoration(
                                        icon: Icon(Icons.account_box_outlined),
                                        border: UnderlineInputBorder(),
                                        labelText: 'Enter your username',
                                      ),
                                    ),
                                ),
                                  Padding(
                                    padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 16),
                                    child: TextFormField(
                                      decoration: const InputDecoration(
                                        icon: Icon(Icons.lock_open),
                                        border: UnderlineInputBorder(),
                                        labelText: 'Enter your Password',
                                      ),
                                    ),
                                  ),
                              ],
                            ),
                            Positioned(
                              left: 209.0,
                              top: 588.0,
                              right: null,
                              bottom: null,
                              width: 145,
                              height: 47,
                              child: RaisedButton(onPressed: (){},
                                color : AppColors.third,
                                shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(15)),
                              child: Text('SignIn',
                              style: TextStyle(
                                fontFamily: 'Montserrat',
                                fontWeight: FontWeight.w700,
                                color: Colors.white,
                              ),),),
                            ),
                            Positioned(
                              top: 676,
                              left: 60,
                              right: 65,
                              bottom: 71,
                              child: Text("Don't have an account ?",
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.w500,
                                  fontFamily: 'Montserrat',
                                  color: Colors.black,
                                ),),
                            ),
                            Positioned(
                              top: 675,
                              left: 250,
                              right: null,
                              width: 100,
                              height: 47,
                              child: InkWell(
                                onTap: () {
                                  Navigator.push(
                                    context,
                                    MaterialPageRoute(builder: (context) => GeneratedSigninWidget()),
                                  );
                                },
                                child: Text("Sign Up",
                                  style: TextStyle(
                                    fontSize: 15,
                                    fontWeight: FontWeight.w900,
                                    fontFamily: 'Montserrat',
                                    color: AppColors.third
                                  ),),
                              ),
                            ),
                            Positioned(
                              top: 720,
                              left: 130,
                              right: null,
                              width: 200,
                              height: 47,
                              child: InkWell(
                                onTap: () {  },
                                child: Text("Continue as a guest",
                                  style: TextStyle(
                                    fontSize: 15,
                                    fontWeight: FontWeight.w500,
                                    fontFamily: 'Montserrat',
                                    color: Colors.black,
                                  ),),
                              ),
                            ),
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
