import 'package:flutter/material.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedSANDYHILLWidget.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedIconlocationWidget3.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedGooglemapsdataconfirmsthetraffictrendseverybodyexpected1.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedIconlocationWidget4.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedFrameWidget2.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedAddNewAddressWidget2.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedVector31Widget3.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedUsemycurrentlocationWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedA28SecondFloorSector64Noida20130102Widget3.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedCENTRETOWNWidget1.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedNavigationMap_PinWidget.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedSearchLocationWidget.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedIconlocationWidget2.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedVector25Widget2.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedA28SecondFloorSector64Noida20130102Widget2.dart';
import 'package:flutterapp/neo2eatapp/generatedchoosewidget/generated/GeneratedVector30Widget1.dart';

/* Frame choose
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChooseWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 940.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget7(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 248.0,
                              height: 27.0,
                              child: GeneratedAddNewAddressWidget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget2(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 395.0,
                              child:
                                  GeneratedGooglemapsdataconfirmsthetraffictrendseverybodyexpected1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 477.0,
                              child: GeneratedRectangle6Widget1(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 635.0,
                              right: null,
                              bottom: null,
                              width: 237.0,
                              height: 54.0,
                              child:
                                  GeneratedA28SecondFloorSector64Noida20130102Widget2(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 746.0,
                              right: null,
                              bottom: null,
                              width: 237.0,
                              height: 54.0,
                              child:
                                  GeneratedA28SecondFloorSector64Noida20130102Widget3(),
                            ),
                            Positioned(
                              left: 195.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 0.0,
                              child: GeneratedVector30Widget1(),
                            ),
                            Positioned(
                              left: -14.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 456.0,
                              height: 111.0,
                              child: GeneratedFrameWidget2(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 517.0,
                              right: null,
                              bottom: null,
                              width: 376.0,
                              height: 48.0,
                              child: GeneratedRectangle7Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 841.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 44.0,
                              child: GeneratedRectangle8Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.3878504672897196;

                                final double height =
                                    constraints.maxHeight * 0.02159827213822894;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.20093457943925233,
                                      y: constraints.maxHeight *
                                          0.5745140388768899,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSearchLocationWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2967289719626168;

                                final double height =
                                    constraints.maxHeight * 0.02159827213822894;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18457943925233644,
                                      y: constraints.maxHeight *
                                          0.6565874730021598,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSANDYHILLWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.352803738317757;

                                final double height = constraints.maxHeight *
                                    0.024838012958963283;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18457943925233644,
                                      y: constraints.maxHeight *
                                          0.7764578833693304,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedCENTRETOWNWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6261682242990654;

                                final double height =
                                    constraints.maxHeight * 0.02591792656587473;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.21495327102803738,
                                      y: constraints.maxHeight *
                                          0.9211663066954644,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedUsemycurrentlocationWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.07710280373831775;

                                final double height = constraints.maxHeight *
                                    0.035637149028077755;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.0911214953271028,
                                      y: constraints.maxHeight *
                                          0.5658747300215983,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSearchWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 847.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 30.0,
                              child: GeneratedNavigationMap_PinWidget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 28.0,
                              child: GeneratedIconlocationWidget2(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 714.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 28.0,
                              child: GeneratedIconlocationWidget3(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 698.0,
                              right: null,
                              bottom: null,
                              width: 389.5,
                              height: 0.0,
                              child: GeneratedVector31Widget3(),
                            ),
                            Positioned(
                              left: 291.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 56.0,
                              child: GeneratedIconlocationWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
