import 'package:flutter/material.dart';

/* Rectangle palette 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPalette1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 406.0,
        height: 361.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/9fefea3495fbc33fc8df4bc9f0b0516e78ad40ad.png",
            color: null,
            fit: BoxFit.cover,
            width: 406.0,
            height: 361.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
