import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedPASSWORDWidget1.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedCreateAccountWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedVector23Widget.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedVector22Widget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedVector25Widget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedVector24Widget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedMailWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedRectangle2Widget2.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedVector21Widget1.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedCreateAccountWidget1.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedCONFIRMPASSWORDWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedFrameWidget1.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedVector19Widget1.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedAlreadyhaveanaccountSigninWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedSIGNUPWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedCONTINUEASAGUESTWidget1.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedPhoneWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedFULLNAMEWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedRectangle1Widget6.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedVectorWidget7.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedPHONENUMBERWidget.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/generated/GeneratedVector20Widget1.dart';

import '../../theme/themee.dart';

/* Frame Sign in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 926.0,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 428.0,
                              height: 926.0,
                              child: Stack(
                                  clipBehavior: Clip.none, fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color: Color.fromARGB(255, 255, 255, 255),
                                      ),
                                    ),
                                    Positioned(
                                      left: -1.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 429.0,
                                      height: 926.0,
                                      child: GeneratedRectangle1Widget6(),
                                    ),
                                    Positioned(
                                      left: 269.4127197265625,
                                      top: -107.6426010131836,
                                      right: null,
                                      bottom: null,
                                      width: 239.564697265625,
                                      height: 251.9700164794922,
                                      child: GeneratedVectorWidget7(),
                                    ),
                                    Positioned(
                                      left: 250.0,
                                      top: 727.0,
                                      right: null,
                                      bottom: null,
                                      width: 145.0,
                                      height: 47.0,
                                      child: RaisedButton(onPressed: (){
                                      },
                                        color : AppColors.third,
                                        shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(15)),
                                        child: Text('Sign Up',
                                          style: TextStyle(
                                            fontFamily: 'Montserrat',
                                            fontWeight: FontWeight.w700,
                                            color: Colors.white,
                                          ),),),
                                    ),
                                    Positioned(
                                      left: 59.0,
                                      top: 837.0,
                                      right: null,
                                      bottom: null,
                                      width: 313.0,
                                      height: 20.0,
                                      child: InkWell(onTap: (){}, child : GeneratedAlreadyhaveanaccountSigninWidget(),),
                                    ),
                                    Positioned(
                                      left: 134.0,
                                      top: 871.0,
                                      right: null,
                                      bottom: null,
                                      width: 163.0,
                                      height: 16.0,
                                      child: InkWell(onTap: (){}, child : GeneratedCONTINUEASAGUESTWidget1(),),
                                    ),
                                    Positioned(
                                      left: 46.0,
                                      top: 193.0,
                                      right: null,
                                      bottom: null,
                                      width: 325.0,
                                      height: 43.0,
                                      child: Text('CREATE  ACCOUNT',
                                      style: TextStyle(
                                        fontFamily: 'Montserrat',
                                        fontWeight: FontWeight.w700,
                                        fontSize: 28,
                                      ),),
                                    ),
                                    Positioned(
                                      left: 20.0,
                                      top: 70.0,
                                      right: null,
                                      bottom: null,
                                      width: 30.0,
                                      height: 30.0,
                                      child: InkWell(onTap: (){
                                        Navigator.pop(context);
                                      }, child : Icon(Icons.arrow_back),),
                                    ),
                                    Column(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Padding(
                                          padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 16),
                                          child: TextFormField(
                                            decoration: const InputDecoration(
                                              icon: Icon(Icons.account_box_outlined),
                                              border: UnderlineInputBorder(),
                                              labelText: 'Enter your username',
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 16),
                                          child: TextFormField(
                                            decoration: const InputDecoration(
                                              icon: Icon(Icons.email_outlined),
                                              border: UnderlineInputBorder(),
                                              labelText: 'Enter your E-mail',
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 16),
                                          child: TextFormField(
                                            decoration: const InputDecoration(
                                              icon: Icon(Icons.phone),
                                              border: UnderlineInputBorder(),
                                              labelText: 'Enter your phone',
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 16),
                                          child: TextFormField(
                                            decoration: const InputDecoration(
                                              icon: Icon(Icons.password),
                                              border: UnderlineInputBorder(),
                                              labelText: 'Enter your password',
                                            ),
                                          ),
                                        ),
                                        Padding(
                                          padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 16),
                                          child: TextFormField(
                                            decoration: const InputDecoration(
                                              icon: Icon(Icons.password),
                                              border: UnderlineInputBorder(),
                                              labelText: 'Re-enter your password',
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ]),
                            ))
                      ])),
                );
              }),
        ));
  }
}
