import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedFrameWidget5.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedPleaseEnterYourPhoneNumberToRecieveaVerificationCodeWid.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedRectangle1Widget11.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedRectangle8Widget3.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedSendCodeWidget1.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedVector26Widget1.dart';
import 'package:untitled5/untitledapp/generatedsendphonewidget/generated/GeneratedWavy_Tech28_Single10Converted11Widget.dart';

import '../../helpers/transform/transform.dart';
import '../generatedsigninwidget/generated/GeneratedPhoneWidget.dart';
import 'generated/GeneratedForgotPasswordWidget1.dart';
import 'generated/GeneratedPHONENUMBERWidget.dart';
import 'generated/GeneratedVector25Widget5.dart';

/* Frame Send phone
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSendphoneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget11(),
                            ),
                            Positioned(
                              left: 98.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 27.0,
                              child: GeneratedForgotPasswordWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget5(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 533.0,
                              right: null,
                              bottom: null,
                              width: 372.0,
                              height: 52.0,
                              child:
                                  GeneratedPleaseEnterYourPhoneNumberToRecieveaVerificationCodeWid(),
                            ),
                            Positioned(
                              left: 45.5,
                              top: 695.4375,
                              right: null,
                              bottom: null,
                              width: 331.0,
                              height: 0.0,
                              child: GeneratedVector26Widget1(),
                            ),
                            Positioned(
                              left: -14.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 456.0,
                              height: 111.0,
                              child: GeneratedFrameWidget5(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 841.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 44.0,
                              child: GeneratedRectangle8Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6261682242990654;

                                final double height =
                                    constraints.maxHeight * 0.02591792656587473;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18925233644859812,
                                      y: constraints.maxHeight *
                                          0.9200863930885529,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSendCodeWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 668.5238037109375,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 15.0,
                              child: GeneratedPHONENUMBERWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.055582830839067975;

                                final double height = constraints.maxHeight *
                                    0.023243813483812898;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.1308411214953271,
                                      y: constraints.maxHeight *
                                          0.7138228941684666,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedPhoneWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 163.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 326.0,
                              child:
                                  GeneratedWavy_Tech28_Single10Converted11Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
