import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/Generated4Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/Generated6Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/Generated8Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/Generated9Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedFrameWidget6.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedPleaseEnterThe4DigitCodeSentToYourEmailWidget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle1Widget12.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle8Widget4.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedResendCodeWidget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector25Widget6.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector34Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector35Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector36Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector37Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVector38Widget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVerifyWidget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedVerifyYourEmailWidget.dart';
import 'package:untitled5/untitledapp/generatedcodeemailwidget/generated/GeneratedWavy_Gen03_Single06Converted1Widget.dart';

import '../../helpers/transform/transform.dart';

/* Frame Code email
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCodeemailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget12(),
                            ),
                            Positioned(
                              left: 92.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 27.0,
                              child: GeneratedVerifyYourEmailWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget6(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 505.0,
                              right: null,
                              bottom: null,
                              width: 372.0,
                              height: 58.0,
                              child:
                                  GeneratedPleaseEnterThe4DigitCodeSentToYourEmailWidget(),
                            ),
                            Positioned(
                              left: -14.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 456.0,
                              height: 111.0,
                              child: GeneratedFrameWidget6(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 841.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 44.0,
                              child: GeneratedRectangle8Widget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.633177570093458;

                                final double height = constraints.maxHeight *
                                    0.029157667386609073;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18925233644859812,
                                      y: constraints.maxHeight *
                                          0.9200863930885529,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedVerifyWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 49.0,
                              child: GeneratedRectangle9Widget(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 42.0,
                              child: Generated8Widget(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 49.0,
                              child: GeneratedRectangle10Widget(),
                            ),
                            Positioned(
                              left: 165.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 0.0,
                              child: GeneratedVector36Widget(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 49.0,
                              child: GeneratedRectangle11Widget(),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 49.0,
                              child: GeneratedRectangle12Widget(),
                            ),
                            Positioned(
                              left: 99.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 0.0,
                              child: GeneratedVector35Widget(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 0.0,
                              child: GeneratedVector37Widget(),
                            ),
                            Positioned(
                              left: 297.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 0.0,
                              child: GeneratedVector38Widget(),
                            ),
                            Positioned(
                              left: 169.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 42.0,
                              child: Generated4Widget(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 42.0,
                              child: Generated6Widget(),
                            ),
                            Positioned(
                              left: 302.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 42.0,
                              child: Generated9Widget(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 724.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 20.0,
                              child: GeneratedResendCodeWidget(),
                            ),
                            Positioned(
                              left: 150.5,
                              top: 749.0,
                              right: null,
                              bottom: null,
                              width: 129.5,
                              height: 0.0,
                              child: GeneratedVector34Widget1(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 135.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 342.0,
                              child:
                                  GeneratedWavy_Gen03_Single06Converted1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
