import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/Generated73432161Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse10Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse11Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse12Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse1Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse2Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse3Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse4Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse5Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse6Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse7Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse8Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedEllipse9Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedGETANYTHINGYOUWANTDELIVEREDTOYOURHOUSEWidget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedVector10Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedVector11Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedVector5Widget2.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedVector6Widget2.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedVector7Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedVector8Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget1/generated/GeneratedVector9Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget2/GeneratedINTROWidget2.dart';

import 'generated/GeneratedNextWidget1.dart';
import 'generated/GeneratedRectangle1Widget2.dart';
import 'generated/GeneratedVector1Widget1.dart';
import 'generated/GeneratedVector2Widget1.dart';
import 'generated/GeneratedVector3Widget2.dart';
import 'generated/GeneratedVector4Widget2.dart';


/* Frame INTRO
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedINTROWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget2(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 251.0,
                              child: GeneratedVector2Widget1(),
                            ),
                            Positioned(
                              left: 311.2862548828125,
                              top: -1.11102294921875,
                              right: null,
                              bottom: null,
                              width: 116.71367645263672,
                              height: 250.61102294921875,
                              child: GeneratedVector1Widget1(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 644.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 281.0,
                              child: GeneratedVector4Widget2(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 592.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 334.0,
                              child: GeneratedVector3Widget2(),
                            ),
                            Positioned(
                              left: 188.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 34.0,
                              child: GeneratedNextWidget1(),
                            ),
                            Positioned(
                              left: 177.0,
                              top: 765.0,
                              right: null,
                              bottom: null,
                              width: 74.0,
                              height: 74.0,
                              child: InkWell(
                                onTap: (){
                                  Navigator.push(
                                    context,
                                    MaterialPageRoute(builder: (context) => GeneratedINTROWidget2()),
                                  );
                                },
                                child: GeneratedEllipse1Widget1(),
                              ),
                            ),
                            Positioned(
                              left: 201.0,
                              top: 793.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 19.0,
                              child: GeneratedVector5Widget2(),
                            ),
                            Positioned(
                              left: 205.0,
                              top: 608.0,
                              right: null,
                              bottom: null,
                              width: 17.0,
                              height: 17.0,
                              child: GeneratedEllipse5Widget1(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 11.0,
                              child: GeneratedEllipse2Widget1(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 11.0,
                              child: GeneratedEllipse3Widget1(),
                            ),
                            Positioned(
                              left: 179.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 11.0,
                              child: GeneratedEllipse4Widget1(),
                            ),
                            Positioned(
                              left: 121.0,
                              top: 390.0,
                              right: null,
                              bottom: null,
                              width: 185.10028076171875,
                              height: 73.2317886352539,
                              child: GeneratedVector6Widget2(),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 506.0,
                              right: null,
                              bottom: null,
                              width: 314.0,
                              height: 62.0,
                              child:
                                  GeneratedGETANYTHINGYOUWANTDELIVEREDTOYOURHOUSEWidget(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedEllipse6Widget1(),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 155.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 10.0,
                              child: GeneratedEllipse7Widget1(),
                            ),
                            Positioned(
                              left: 323.0,
                              top: 228.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 10.0,
                              child: GeneratedEllipse8Widget1(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 242.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse9Widget1(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 328.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse12Widget1(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 278.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse11Widget1(),
                            ),
                            Positioned(
                              left: 251.0,
                              top: 353.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse10Widget1(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 19.5,
                              child: GeneratedVector7Widget1(),
                            ),
                            Positioned(
                              left: 395.0,
                              top: 377.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 9.0,
                              child: GeneratedVector8Widget1(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 5.0,
                              height: 6.0,
                              child: GeneratedVector9Widget1(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 165.0,
                              right: null,
                              bottom: null,
                              width: 5.0,
                              height: 6.0,
                              child: GeneratedVector10Widget1(),
                            ),
                            Positioned(
                              left: 42.5,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 316.5,
                              height: 24.5,
                              child: GeneratedVector11Widget1(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 157.0,
                              right: null,
                              bottom: null,
                              width: 450.0,
                              height: 315.0,
                              child: Generated73432161Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
