import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse10Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse11Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse12Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse13Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse15Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse16Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse17Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse18Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse19Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse6Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse7Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse8Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedEllipse9Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedFiuserWidget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedPleaseenteradeliveryaddressWidget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedRectangle1Widget4.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedUsecurrentlocationWidget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector10Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector12Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector15Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector16Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector17Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector18Widget.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector7Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector8Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedVector9Widget3.dart';
import 'package:untitled5/untitledapp/generatedselectyoucountryregionwidget/generated/GeneratedWavy_Bus26_Single10Converted1Widget.dart';


/* Frame Select you Country/Region
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelectyouCountryRegionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget4(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 823.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 55.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 810.0,
                              right: null,
                              bottom: null,
                              width: 366.0,
                              height: 55.0,
                              child: InkWell(
                                onTap: (){},
                                child: GeneratedRectangle2Widget(),
                              ),
                            ),
                            Positioned(
                              left: 111.0,
                              top: 823.0,
                              right: null,
                              bottom: null,
                              width: 208.0,
                              height: 32.0,
                              child: InkWell(
                                onTap: (){},
                                child: GeneratedUsecurrentlocationWidget(),
                              ),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 38.0,
                              right: null,
                              bottom: null,
                              width: 292.0,
                              height: 44.0,
                              child:
                                  GeneratedPleaseenteradeliveryaddressWidget(),
                            ),
                            Positioned(
                              left: 374.0,
                              top: 48.07916259765625,
                              right: null,
                              bottom: null,
                              width: 20.934501647949219,
                              height: 20.3543853759765625,
                              child: InkWell(
                                onTap: (){},
                                child: GeneratedVector12Widget(),
                              ),
                            ),
                            Positioned(
                              left: 374.0,
                              top: 46.0645751953125,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child:
                              InkWell(
                                onTap: (){},
                                child: GeneratedVector12Widget(),
                              ),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 35.0,
                              height: 35.0,
                              child: GeneratedEllipse19Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 32.0,
                              right: null,
                              bottom: null,
                              width: 35.0,
                              height: 35.0,
                              child: InkWell(
                                onTap: (){},
                                child: GeneratedEllipse13Widget(),
                              ) ,
                            ),
                            Positioned(
                              left: 25.0,
                              top: 38.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 22.0,
                              child:  InkWell(
                                onTap: (){},
                                child: GeneratedFiuserWidget(),
                              ) ,
                            ),
                            Positioned(
                              left: 63.0,
                              top: 270.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedEllipse6Widget3(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 663.0,
                              right: null,
                              bottom: null,
                              width: 12.0,
                              height: 12.0,
                              child: GeneratedEllipse15Widget(),
                            ),
                            Positioned(
                              left: 144.0,
                              top: 212.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 10.0,
                              child: GeneratedEllipse7Widget3(),
                            ),
                            Positioned(
                              left: 144.0,
                              top: 721.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 10.0,
                              child: GeneratedEllipse16Widget(),
                            ),
                            Positioned(
                              left: 349.0,
                              top: 249.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 10.0,
                              child: GeneratedEllipse8Widget3(),
                            ),
                            Positioned(
                              left: 349.0,
                              top: 684.0,
                              right: null,
                              bottom: null,
                              width: 10.0,
                              height: 10.0,
                              child: GeneratedEllipse17Widget(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 213.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse9Widget3(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 720.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse18Widget(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 328.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse12Widget3(),
                            ),
                            Positioned(
                              left: 255.0,
                              top: 278.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse11Widget3(),
                            ),
                            Positioned(
                              left: 251.0,
                              top: 353.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 7.0,
                              child: GeneratedEllipse10Widget3(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 177.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 19.5,
                              child: GeneratedVector7Widget3(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 756.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 19.5,
                              child: GeneratedVector15Widget(),
                            ),
                            Positioned(
                              left: 395.0,
                              top: 377.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 9.0,
                              child: GeneratedVector8Widget3(),
                            ),
                            Positioned(
                              left: 395.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 7.0,
                              height: 9.0,
                              child: GeneratedVector16Widget(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 327.0,
                              right: null,
                              bottom: null,
                              width: 5.0,
                              height: 6.0,
                              child: GeneratedVector9Widget3(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 181.0,
                              right: null,
                              bottom: null,
                              width: 5.0,
                              height: 6.0,
                              child: GeneratedVector10Widget3(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 752.0,
                              right: null,
                              bottom: null,
                              width: 5.0,
                              height: 6.0,
                              child: GeneratedVector17Widget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 274.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 378.0,
                              child:
                                  GeneratedWavy_Bus26_Single10Converted1Widget(),
                            ),
                            Positioned(
                              left: 160,
                              top: 890.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 378.0,
                              child: InkWell(
                                onTap: (){},
                                child: Text('Skip this step',
                                style: TextStyle(
                                  fontFamily: 'Montserrat',
                                  fontSize: 15,
                                  color: Colors.white,
                                  fontWeight: FontWeight.w500,
                                ),),
                              )
                              ,
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
