import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/Generated4Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/Generated6Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/Generated8Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/Generated9Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedFrameWidget7.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedPleaseEnterThe4DigitCodeSentToYourPhoneNumberWidget.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle12Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle1Widget13.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle8Widget5.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedRectangle9Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedResendCodeWidget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector25Widget7.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector34Widget2.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector35Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector36Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVector37Widget1.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedVerifyYourPhoneNumberWidget.dart';
import 'package:untitled5/untitledapp/generatedcodephonewidget/generated/GeneratedWavy_Gen01_Single02Converted1Widget.dart';

import '../../helpers/transform/transform.dart';
import 'generated/GeneratedVerifyWidget1.dart';

/* Frame Code phone
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCodephoneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget13(),
                            ),
                            Positioned(
                              left: 93.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 268.0,
                              height: 58.0,
                              child: GeneratedVerifyYourPhoneNumberWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget7(),
                            ),
                            Positioned(
                              left: -14.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 456.0,
                              height: 111.0,
                              child: GeneratedFrameWidget7(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 841.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 44.0,
                              child: GeneratedRectangle8Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.633177570093458;

                                final double height = constraints.maxHeight *
                                    0.029157667386609073;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18925233644859812,
                                      y: constraints.maxHeight *
                                          0.9200863930885529,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedVerifyWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 506.0,
                              right: null,
                              bottom: null,
                              width: 372.0,
                              height: 58.0,
                              child:
                                  GeneratedPleaseEnterThe4DigitCodeSentToYourPhoneNumberWidget(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 49.0,
                              child: GeneratedRectangle9Widget1(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 42.0,
                              child: Generated8Widget1(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 49.0,
                              child: GeneratedRectangle10Widget1(),
                            ),
                            Positioned(
                              left: 165.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 0.0,
                              child: GeneratedVector36Widget1(),
                            ),
                            Positioned(
                              left: 222.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 49.0,
                              child: GeneratedRectangle11Widget1(),
                            ),
                            Positioned(
                              left: 288.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 49.0,
                              child: GeneratedRectangle12Widget1(),
                            ),
                            Positioned(
                              left: 99.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 0.0,
                              child: GeneratedVector35Widget1(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 0.0,
                              child: GeneratedVector37Widget1(),
                            ),
                            Positioned(
                              left: 169.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 42.0,
                              child: Generated4Widget1(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 42.0,
                              child: Generated6Widget1(),
                            ),
                            Positioned(
                              left: 302.0,
                              top: 625.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 42.0,
                              child: Generated9Widget1(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 724.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 20.0,
                              child: GeneratedResendCodeWidget1(),
                            ),
                            Positioned(
                              left: 150.5,
                              top: 749.0,
                              right: null,
                              bottom: null,
                              width: 129.5,
                              height: 0.0,
                              child: GeneratedVector34Widget2(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 143.0,
                              right: null,
                              bottom: null,
                              width: 336.0,
                              height: 334.0,
                              child:
                                  GeneratedWavy_Gen01_Single02Converted1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
