import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedsigninwidget/GeneratedSigninWidget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedImage1Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedVector3Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedVector4Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedVector5Widget.dart';
import 'package:untitled5/untitledapp/generatedsplashscreenwidget/generated/GeneratedVector6Widget.dart';
import 'package:untitled5/theme/themee.dart';
import 'package:easy_splash_screen/easy_splash_screen.dart';

/* Frame Splash Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
       return EasySplashScreen(
        logo: Image.asset(
            'assets/images/2285b8a80a7a1c2ea3581eedddd46628faebbd87.png',
            width: 500,
          height: 500,
        ),
        title: Text(
          "Neo2Eat",
          style: TextStyle(
            fontSize: 30,
            fontWeight: FontWeight.bold,
            fontFamily: 'Montserrat',
            color: Colors.white,
          ),
        ),
        backgroundColor: AppColors.third,
        showLoader: false,
        durationInSeconds:9,
        navigator: GeneratedSigninWidget(),
     );
  }

}