import 'package:flutter/material.dart';
import 'package:untitled5/helpers/transform/transform.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedAddNewAddressWidget3.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedAddressTypeWidget1.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedDoneWidget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedEllipse23Widget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedFileNote_EditWidget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedGooglemapsdataconfirmsthetraffictrendseverybodyexpected2.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedGroup6Widget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedHomeWidget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedIdrathertypemyownWidget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedMenuClose_SMWidget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedNavigationHouse_03Widget1.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedRectangle1Widget8.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedRectangle6Widget2.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedVector25Widget3.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedVector30Widget2.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedVector31Widget4.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedVector32Widget1.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedVector33Widget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedWarningCircle_CheckWidget.dart';
import 'package:untitled5/untitledapp/generatedchoosetypewidget/generated/GeneratedWorkWidget.dart';

/* Frame choose Type
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChooseTypeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 940.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget8(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 248.0,
                              height: 27.0,
                              child: GeneratedAddNewAddressWidget3(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget3(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 395.0,
                              child:
                                  GeneratedGooglemapsdataconfirmsthetraffictrendseverybodyexpected2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 804.0,
                              child: GeneratedRectangle6Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.14953271028037382;

                                final double height = constraints.maxHeight *
                                    0.024838012958963283;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2850467289719626,
                                      y: constraints.maxHeight *
                                          0.35853131749460043,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedHomeWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.13551401869158877;

                                final double height = constraints.maxHeight *
                                    0.024838012958963283;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.29439252336448596,
                                      y: constraints.maxHeight *
                                          0.4816414686825054,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedWorkWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 399.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 78.0,
                              child: GeneratedGroup6Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.1705607476635514;

                                final double height =
                                    constraints.maxHeight * 0.07883369330453564;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07009345794392523,
                                      y: constraints.maxHeight *
                                          0.31533477321814257,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedNavigationHouse_03Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 384.0,
                              right: null,
                              bottom: null,
                              width: 389.5,
                              height: 0.0,
                              child: GeneratedVector31Widget4(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 499.0,
                              right: null,
                              bottom: null,
                              width: 389.5,
                              height: 0.0,
                              child: GeneratedVector33Widget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 26.0,
                              child: GeneratedEllipse23Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 188.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedMenuClose_SMWidget(),
                            ),
                            Positioned(
                              left: 195.0,
                              top: 159.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 0.0,
                              child: GeneratedVector30Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.397196261682243;

                                final double height = constraints.maxHeight *
                                    0.026997840172786176;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3037383177570093,
                                      y: constraints.maxHeight *
                                          0.20302375809935205,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedAddressTypeWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.5186915887850467;

                                final double height = constraints.maxHeight *
                                    0.020518358531317494;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.2827102803738318,
                                      y: constraints.maxHeight *
                                          0.593952483801296,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedIdrathertypemyownWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 699.5,
                              right: null,
                              bottom: null,
                              width: 6.0,
                              height: 9.0,
                              child: GeneratedVector32Widget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 521.0,
                              right: null,
                              bottom: null,
                              width: 67.0,
                              height: 67.0,
                              child: GeneratedFileNote_EditWidget(),
                            ),
                            Positioned(
                              left: 360.0,
                              top: 322.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedWarningCircle_CheckWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.1378504672897196;

                                final double height = constraints.maxHeight *
                                    0.024838012958963283;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8247663551401869,
                                      y: constraints.maxHeight *
                                          0.2084233261339093,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedDoneWidget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
