import 'package:flutter/material.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedNavigationHouse_03Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedVector21Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedNameSurnameWidget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedMyOfficeWidget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedEditEdit_Pencil_01Widget2.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedSENDTOWidget1.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedSENDTOWidget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedFrameWidget1.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedDeliveryAddressWidget1.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedAddNewAddressWidget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedEditEdit_Pencil_01Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedEllipse20Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedCONTINUEWidget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedRectangle1Widget5.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedEllipse22Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedVector31Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedNavigationHouse_AddWidget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedA28SecondFloorSector64Noida20130102Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedFrameWidget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedEllipse21Widget1.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedMyHomeWidget.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedEditEdit_Pencil_01Widget1.dart';
import 'package:flutterapp/neo2eatapp/generatednewaddresswidget/generated/GeneratedVector25Widget.dart';

/* Frame New address
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewaddressWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget5(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 667.0,
                              right: null,
                              bottom: null,
                              width: 252.0,
                              height: 27.0,
                              child: GeneratedAddNewAddressWidget(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 238.0,
                              height: 27.0,
                              child: GeneratedDeliveryAddressWidget1(),
                            ),
                            Positioned(
                              left: 325.0,
                              top: 653.0,
                              right: null,
                              bottom: null,
                              width: 47.0,
                              height: 47.0,
                              child: GeneratedNavigationHouse_AddWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 199.0,
                              right: null,
                              bottom: null,
                              width: 376.0,
                              height: 71.0,
                              child: GeneratedRectangle4Widget(),
                            ),
                            Positioned(
                              left: -54.0,
                              top: 246.0,
                              right: null,
                              bottom: null,
                              width: 536.0,
                              height: 179.0,
                              child: GeneratedFrameWidget(),
                            ),
                            Positioned(
                              left: 7.0,
                              top: 295.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 78.0,
                              child: GeneratedRectangle5Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 397.0,
                              right: null,
                              bottom: null,
                              width: 376.0,
                              height: 144.0,
                              child: GeneratedRectangle5Widget1(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 224.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 22.0,
                              child: GeneratedEllipse20Widget(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 425.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 22.0,
                              child: GeneratedEllipse21Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.07009345794392523;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        30.0;

                                double percentHeight = 0.032397408207343416;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        30.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.0630841121495327,
                                      translateY: constraints.maxHeight *
                                          0.3466522678185745,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedEllipse21Widget1())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 215.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 20.0,
                              child: GeneratedSENDTOWidget(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 427.0,
                              right: null,
                              bottom: null,
                              width: 157.0,
                              height: 20.0,
                              child: GeneratedNameSurnameWidget(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 456.0,
                              right: null,
                              bottom: null,
                              width: 237.0,
                              height: 54.0,
                              child:
                                  GeneratedA28SecondFloorSector64Noida20130102Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2102803738317757;

                                final double height =
                                    constraints.maxHeight * 0.02159827213822894;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3621495327102804,
                                      y: constraints.maxHeight *
                                          0.33801295896328293,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSENDTOWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2219626168224299;

                                final double height =
                                    constraints.maxHeight * 0.02159827213822894;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3621495327102804,
                                      y: constraints.maxHeight *
                                          0.36285097192224625,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedMyHomeWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2219626168224299;

                                final double height =
                                    constraints.maxHeight * 0.02159827213822894;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.37383177570093457,
                                      y: constraints.maxHeight *
                                          0.2591792656587473,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedMyOfficeWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.037383177570093455;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        16.0;

                                double percentHeight = 0.017278617710583154;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        16.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.0794392523364486,
                                      translateY: constraints.maxHeight *
                                          0.3542116630669546,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedEllipse22Widget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.15186915887850466;

                                final double height =
                                    constraints.maxHeight * 0.07019438444924406;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.1588785046728972,
                                      y: constraints.maxHeight *
                                          0.3228941684665227,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedNavigationHouse_03Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 76.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 78.0,
                              child: GeneratedGroup7Widget(),
                            ),
                            Positioned(
                              left: 365.0,
                              top: 314.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 34.0,
                              child: GeneratedEditEdit_Pencil_01Widget(),
                            ),
                            Positioned(
                              left: 343.0,
                              top: 218.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 34.0,
                              child: GeneratedEditEdit_Pencil_01Widget1(),
                            ),
                            Positioned(
                              left: 343.0,
                              top: 419.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 34.0,
                              child: GeneratedEditEdit_Pencil_01Widget2(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 192.0,
                              height: 97.0,
                              child: GeneratedFrameWidget1(),
                            ),
                            Positioned(
                              left: 136.0,
                              top: 833.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 47.0,
                              child: GeneratedRectangle2Widget1(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 849.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedCONTINUEWidget(),
                            ),
                            Positioned(
                              left: 244.0,
                              top: 857.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 0.0,
                              child: GeneratedVector21Widget(),
                            ),
                            Positioned(
                              left: 195.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 0.0,
                              child: GeneratedVector31Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
