import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedA28SecondFloorSector64Noida20130102Widget1.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedAddressTypeWidget.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedCENTRETOWNWidget.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedGooglemapsdataconfirmsthetraffictrendseverybodyexpected.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedHomeWorkWidget.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedIconlocationWidget.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedIconlocationWidget1.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedRectangle6Widget.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedRectangle8Widget.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedVector30Widget.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedVector31Widget1.dart';
import 'package:untitled5/untitledapp/generatedtypewidget/generated/GeneratedVector32Widget.dart';

import '../../helpers/transform/transform.dart';
import '../generatedsigninwidget/generated/GeneratedRectangle1Widget6.dart';
import 'generated/GeneratedAddNewAddressWidget1.dart';
import 'generated/GeneratedVector25Widget1.dart';


/* Frame Type
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTypeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 940.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget6(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 248.0,
                              height: 27.0,
                              child: GeneratedAddNewAddressWidget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget1(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 108.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 395.0,
                              child:
                                  GeneratedGooglemapsdataconfirmsthetraffictrendseverybodyexpected(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 477.0,
                              child: GeneratedRectangle6Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 662.0,
                              right: null,
                              bottom: null,
                              width: 389.5,
                              height: 0.0,
                              child: GeneratedVector31Widget1(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 237.0,
                              height: 54.0,
                              child:
                                  GeneratedA28SecondFloorSector64Noida20130102Widget1(),
                            ),
                            Positioned(
                              left: 195.0,
                              top: 490.0,
                              right: null,
                              bottom: null,
                              width: 38.0,
                              height: 0.0,
                              child: GeneratedVector30Widget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 841.0,
                              right: null,
                              bottom: null,
                              width: 374.0,
                              height: 44.0,
                              child: GeneratedRectangle8Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.32009345794392524;

                                final double height =
                                    constraints.maxHeight * 0.02159827213822894;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.11682242990654206,
                                      y: constraints.maxHeight *
                                          0.9222462203023758,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedAddressTypeWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.24299065420560748;

                                final double height = constraints.maxHeight *
                                    0.017278617710583154;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.6051401869158879,
                                      y: constraints.maxHeight *
                                          0.9265658747300216,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedHomeWorkWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.352803738317757;

                                final double height = constraints.maxHeight *
                                    0.024838012958963283;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18457943925233644,
                                      y: constraints.maxHeight *
                                          0.6047516198704104,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedCENTRETOWNWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 56.0,
                              child: GeneratedIconlocationWidget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 555.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 28.0,
                              child: GeneratedIconlocationWidget1(),
                            ),
                            Positioned(
                              left: 375.0,
                              top: 860.5,
                              right: null,
                              bottom: null,
                              width: 6.0,
                              height: 9.0,
                              child: GeneratedVector32Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
