import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedEMAILWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedForgotPasswordWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedFrameWidget4.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedPleaseEnterYourEmailAddressToRecieveaVerificationCodeWi.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedRectangle1Widget10.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedRectangle8Widget2.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedSendCodeWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedTryAnotherMethodWidget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedVector25Widget4.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedVector34Widget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedWavy_Tech28_Single10Converted11Widget.dart';
import 'package:untitled5/untitledapp/generatedsendemailwidget/generated/GeneratedWavy_Tech28_Single10Converted1Widget.dart';

import '../../helpers/transform/transform.dart';
import 'generated/GeneratedMailWidget.dart';
import 'generated/GeneratedVector26Widget.dart';

/* Frame Send email
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSendemailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none, fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 428.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 429.0,
                              height: 926.0,
                              child: GeneratedRectangle1Widget10(),
                            ),
                            Positioned(
                              left: 98.0,
                              top: 57.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 27.0,
                              child: GeneratedForgotPasswordWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 0.0,
                              child: GeneratedVector25Widget4(),
                            ),
                            Positioned(
                              left: 33.0,
                              top: 533.0,
                              right: null,
                              bottom: null,
                              width: 364.0,
                              height: 52.0,
                              child:
                                  GeneratedPleaseEnterYourEmailAddressToRecieveaVerificationCodeWi(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 742.0,
                              right: null,
                              bottom: null,
                              width: 196.0,
                              height: 20.0,
                              child: GeneratedTryAnotherMethodWidget(),
                            ),
                            Positioned(
                              left: 45.5,
                              top: 695.4375,
                              right: null,
                              bottom: null,
                              width: 331.0,
                              height: 0.0,
                              child: GeneratedVector26Widget(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 668.4375,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 18.0,
                              child: GeneratedEMAILWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.05018285056140935;

                                final double height = constraints.maxHeight *
                                    0.016671166306695465;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.12383177570093458,
                                      y: constraints.maxHeight *
                                          0.7192224622030238,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedMailWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 114.0,
                              top: 767.0,
                              right: null,
                              bottom: null,
                              width: 204.0,
                              height: 0.0,
                              child: GeneratedVector34Widget(),
                            ),
                            Positioned(
                              left: -14.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 456.0,
                              height: 111.0,
                              child: GeneratedFrameWidget4(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 841.0,
                              right: null,
                              bottom: null,
                              width: 347.0,
                              height: 44.0,
                              child: GeneratedRectangle8Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.6261682242990654;

                                final double height =
                                    constraints.maxHeight * 0.02591792656587473;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.18925233644859812,
                                      y: constraints.maxHeight *
                                          0.9200863930885529,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSendCodeWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 171.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 321.0,
                              child:
                                  GeneratedWavy_Tech28_Single10Converted1Widget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 163.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 326.0,
                              child:
                                  GeneratedWavy_Tech28_Single10Converted11Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
