import 'package:flutter/material.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector8Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse9Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector5Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector11Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector10Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedNextWidget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse11Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse1Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse8Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector1Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse3Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector6Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse10Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse12Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse4Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector7Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse7Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector2Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse6Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/Generated299967Converted1Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector9Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/Generated29996Converted1Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse2Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector4Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/Generated29996Converted2Widget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedVector3Widget1.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedRESERVEATYOURFAVORITERESTAURANTWidget.dart';
import 'package:untitled5/untitledapp/generatedintrowidget/generated/GeneratedEllipse5Widget.dart';

import '../generatedintrowidget1/GeneratedINTROWidget1.dart';

/* Frame INTRO
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedINTROWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 926.0,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 428.0,
                              height: 926.0,
                              child: Stack(
                                  clipBehavior: Clip.none, fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color: Color.fromARGB(255, 255, 255, 255),
                                      ),
                                    ),
                                    Positioned(
                                      left: -1.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 429.0,
                                      height: 926.0,
                                      child: GeneratedRectangle1Widget1(),
                                    ),
                                    Positioned(
                                      left: -1.0,
                                      top: 196.0,
                                      right: null,
                                      bottom: null,
                                      width: 78.0,
                                      height: 251.0,
                                      child: GeneratedVector2Widget(),
                                    ),
                                    Positioned(
                                      left: 311.2862548828125,
                                      top: -1.11102294921875,
                                      right: null,
                                      bottom: null,
                                      width: 116.71367645263672,
                                      height: 250.61102294921875,
                                      child: GeneratedVector1Widget(),
                                    ),
                                    Positioned(
                                      left: -1.0,
                                      top: 644.0,
                                      right: null,
                                      bottom: null,
                                      width: 429.0,
                                      height: 281.0,
                                      child: GeneratedVector4Widget1(),
                                    ),
                                    Positioned(
                                      left: -1.0,
                                      top: 592.0,
                                      right: null,
                                      bottom: null,
                                      width: 429.0,
                                      height: 334.0,
                                      child: GeneratedVector3Widget1(),
                                    ),
                                    Positioned(
                                      left: 177.0,
                                      top: 765.0,
                                      right: null,
                                      bottom: null,
                                      width: 74.0,
                                      height: 74.0,
                                      child: InkWell(
                                        onTap: (){
                                          Navigator.push(
                                            context,
                                            MaterialPageRoute(builder: (context) => GeneratedINTROWidget1()),
                                          );
                                        },
                                        child: GeneratedEllipse1Widget(),
                                      ),
                                    ),
                                    Positioned(
                                      left: 201.0,
                                      top: 793.0,
                                      right: null,
                                      bottom: null,
                                      width: 25.0,
                                      height: 19.0,
                                      child: GeneratedVector5Widget1(),
                                    ),
                                    Positioned(
                                      left: 188.0,
                                      top: 858.0,
                                      right: null,
                                      bottom: null,
                                      width: 57.0,
                                      height: 34.0,
                                      child: GeneratedNextWidget(),
                                    ),
                                    Positioned(
                                      left: 176.0,
                                      top: 608.0,
                                      right: null,
                                      bottom: null,
                                      width: 17.0,
                                      height: 17.0,
                                      child: GeneratedEllipse5Widget(),
                                    ),
                                    Positioned(
                                      left: 179.0,
                                      top: 611.0,
                                      right: null,
                                      bottom: null,
                                      width: 11.0,
                                      height: 11.0,
                                      child: GeneratedEllipse2Widget(),
                                    ),
                                    Positioned(
                                      left: 208.0,
                                      top: 611.0,
                                      right: null,
                                      bottom: null,
                                      width: 11.0,
                                      height: 11.0,
                                      child: GeneratedEllipse3Widget(),
                                    ),
                                    Positioned(
                                      left: 237.0,
                                      top: 611.0,
                                      right: null,
                                      bottom: null,
                                      width: 11.0,
                                      height: 11.0,
                                      child: GeneratedEllipse4Widget(),
                                    ),
                                    Positioned(
                                      left: 121.0,
                                      top: 392.0,
                                      right: null,
                                      bottom: null,
                                      width: 185.10028076171875,
                                      height: 73.2317886352539,
                                      child: GeneratedVector6Widget1(),
                                    ),
                                    Positioned(
                                      left: 56.0,
                                      top: 506.0,
                                      right: null,
                                      bottom: null,
                                      width: 318.0,
                                      height: 62.0,
                                      child:
                                      GeneratedRESERVEATYOURFAVORITERESTAURANTWidget(),
                                    ),
                                    Positioned(
                                      left: 5.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 100.0,
                                      height: 100.0,
                                      child: Generated29996Converted1Widget(),
                                    ),
                                    Positioned(
                                      left: 90.0,
                                      top: 269.0,
                                      right: null,
                                      bottom: null,
                                      width: 12.0,
                                      height: 12.0,
                                      child: GeneratedEllipse6Widget(),
                                    ),
                                    Positioned(
                                      left: 191.0,
                                      top: 155.0,
                                      right: null,
                                      bottom: null,
                                      width: 10.0,
                                      height: 10.0,
                                      child: GeneratedEllipse7Widget(),
                                    ),
                                    Positioned(
                                      left: 323.0,
                                      top: 228.0,
                                      right: null,
                                      bottom: null,
                                      width: 10.0,
                                      height: 10.0,
                                      child: GeneratedEllipse8Widget(),
                                    ),
                                    Positioned(
                                      left: 194.0,
                                      top: 242.0,
                                      right: null,
                                      bottom: null,
                                      width: 7.0,
                                      height: 7.0,
                                      child: GeneratedEllipse9Widget(),
                                    ),
                                    Positioned(
                                      left: 202.0,
                                      top: 328.0,
                                      right: null,
                                      bottom: null,
                                      width: 7.0,
                                      height: 7.0,
                                      child: GeneratedEllipse12Widget(),
                                    ),
                                    Positioned(
                                      left: 220.0,
                                      top: 278.0,
                                      right: null,
                                      bottom: null,
                                      width: 7.0,
                                      height: 7.0,
                                      child: GeneratedEllipse11Widget(),
                                    ),
                                    Positioned(
                                      left: 251.0,
                                      top: 353.0,
                                      right: null,
                                      bottom: null,
                                      width: 7.0,
                                      height: 7.0,
                                      child: GeneratedEllipse10Widget(),
                                    ),
                                    Positioned(
                                      left: 282.0,
                                      top: 177.0,
                                      right: null,
                                      bottom: null,
                                      width: 15.0,
                                      height: 19.5,
                                      child: GeneratedVector7Widget(),
                                    ),
                                    Positioned(
                                      left: 395.0,
                                      top: 377.0,
                                      right: null,
                                      bottom: null,
                                      width: 7.0,
                                      height: 9.0,
                                      child: GeneratedVector8Widget(),
                                    ),
                                    Positioned(
                                      left: 131.0,
                                      top: 327.0,
                                      right: null,
                                      bottom: null,
                                      width: 5.0,
                                      height: 6.0,
                                      child: GeneratedVector9Widget(),
                                    ),
                                    Positioned(
                                      left: 53.0,
                                      top: 165.0,
                                      right: null,
                                      bottom: null,
                                      width: 5.0,
                                      height: 6.0,
                                      child: GeneratedVector10Widget(),
                                    ),
                                    Positioned(
                                      left: 42.5,
                                      top: 426.0,
                                      right: null,
                                      bottom: null,
                                      width: 316.5,
                                      height: 24.5,
                                      child: GeneratedVector11Widget(),
                                    ),
                                    Positioned(
                                      left: 98.0,
                                      top: -45.0,
                                      right: null,
                                      bottom: null,
                                      width: 596.0,
                                      height: 551.0,
                                      child: Generated29996Converted2Widget(),
                                    ),
                                    Positioned(
                                      left: 60.0,
                                      top: 190.0,
                                      right: null,
                                      bottom: null,
                                      width: 350.0,
                                      height: 350.0,
                                      child: Generated299967Converted1Widget(),
                                    )
                                  ]),
                            ))
                      ])),
                );
              }),
        ));
  }
}
